services:
  rtsp_server:
    image: bluenviron/mediamtx:1.6.0-ffmpeg
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - ./stream-server/stream-server-configuration.yaml:/mediamtx.yml
      - ../videos:/videos
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: "${UID}:${GID}"
    restart: unless-stopped